# fly.toml app configuration file generated for divemap on 2025-07-27T18:05:39+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'divemap'
primary_region = 'fra'

[build]
  [build.args]
    REACT_APP_API_URL = "https://divemap-backend.fly.dev"
    # REACT_APP_GOOGLE_CLIENT_ID will be provided via build secrets

[env]
  NODE_ENV = 'production'

[processes]
  app = 'npx serve -s build -l 8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
