---
name: Frontend Tests

on:
  pull_request:
    branches: [main, master]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-tests.yml'
      - 'package.json'
      - 'package-lock.json'
      - 'frontend/package.json'
      - 'frontend/package-lock.json'
  push:
    branches: [main, master]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-tests.yml'
      - 'package.json'
      - 'package-lock.json'
      - 'frontend/package.json'
      - 'frontend/package-lock.json'

jobs:
  test-frontend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.4.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Cache node modules
        uses: actions/cache@v4.2.3
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          cd frontend
          npm ci --prefer-offline --no-audit --no-fund

      - name: Verify React app can build
        run: |
          cd frontend
          npm run build
        env:
          CI: true
          GENERATE_SOURCEMAP: false

      - name: Verify package.json syntax
        run: |
          cd frontend
          node -e "JSON.parse(require('fs').readFileSync('package.json', 'utf8'))"
          echo "✅ package.json syntax is valid"

      - name: Run linting and type checking
        run: |
          cd frontend
          npm run build --if-present
          npx eslint src/ --ext .js,.jsx --max-warnings 0 || \
            echo "⚠️  Linting warnings found (non-blocking)"
        continue-on-error: true

      - name: Run unit tests
        run: |
          cd frontend
          npm test -- --watchAll=false --coverage --passWithNoTests --ci --silent
        env:
          CI: true

      - name: Start frontend development server
        run: |
          cd frontend
          echo "Starting React development server..."
          npm start &
          SERVER_PID=$!
          echo "Server PID: $SERVER_PID"
          echo "Waiting for server to start..."
          sleep 30
          echo "Checking if server is running..."
          if curl -f http://localhost:3000; then
            echo "✅ Server is running successfully"
          else
            echo "❌ Server failed to start"
            echo "Checking server process..."
            ps aux | grep "react-scripts" || echo "No react-scripts process found"
            echo "Checking port 3000..."
            netstat -tlnp | grep :3000 || echo "Port 3000 not in use"
            echo "Checking for any error logs..."
            if [ -f "npm-debug.log" ]; then
              cat npm-debug.log
            fi
            exit 1
          fi
        env:
          CI: true
          BROWSER: none
          REACT_APP_API_URL: "http://localhost:8000"

      - name: Run frontend validation tests
        run: |
          cd frontend
          npm run test:validation
        env:
          CI: true
          TEST_ACCESSIBILITY: true
        timeout-minutes: 10

      - name: Run frontend integration tests
        run: |
          cd frontend
          npm run test:frontend
        env:
          CI: true
        timeout-minutes: 15

      - name: Run end-to-end tests
        run: |
          cd frontend
          npm run test:e2e
        env:
          CI: true
        timeout-minutes: 20

      - name: Upload test results
        uses: actions/upload-artifact@v4.6.2
        if: always()
        with:
          name: frontend-test-results-${{ matrix.node-version }}
          path: |
            frontend/coverage/
            frontend/test-results/
            frontend/.nyc_output/
            frontend/accessibility-results/

      - name: Upload coverage reports
        uses: codecov/codecov-action@v5.4.3
        with:
          directory: ./frontend/
          flags: frontend
          name: frontend-coverage-${{ matrix.node-version }}
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}

  test-frontend-build:
    runs-on: ubuntu-latest
    needs: test-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Cache node modules
        uses: actions/cache@v4.2.3
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          cd frontend
          npm ci --prefer-offline --no-audit --no-fund

      - name: Verify React app can build
        run: |
          cd frontend
          npm run build
        env:
          CI: true
          GENERATE_SOURCEMAP: false

      - name: Build frontend
        run: |
          cd frontend
          npm run build
        env:
          CI: true
          GENERATE_SOURCEMAP: false

      - name: Verify build output
        run: |
          cd frontend
          if [ ! -d "build" ]; then
            echo "❌ Build directory not found"
            exit 1
          fi
          if [ ! -f "build/index.html" ]; then
            echo "❌ index.html not found in build"
            exit 1
          fi
          echo "✅ Build verification passed"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4.6.2
        if: always()
        with:
          name: frontend-build
          path: frontend/build/

  test-frontend-accessibility:
    runs-on: ubuntu-latest
    needs: test-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Cache node modules
        uses: actions/cache@v4.2.3
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          cd frontend
          npm ci --prefer-offline --no-audit --no-fund

      - name: Verify React app can build
        run: |
          cd frontend
          npm run build
        env:
          CI: true
          GENERATE_SOURCEMAP: false

      - name: Start frontend server
        run: |
          cd frontend
          echo "Starting React development server..."
          npm start &
          SERVER_PID=$!
          echo "Server PID: $SERVER_PID"
          echo "Waiting for server to start..."
          sleep 30
          echo "Checking if server is running..."
          if curl -f http://localhost:3000; then
            echo "✅ Server is running successfully"
          else
            echo "❌ Server failed to start"
            echo "Checking server process..."
            ps aux | grep "react-scripts" || echo "No react-scripts process found"
            echo "Checking port 3000..."
            netstat -tlnp | grep :3000 || echo "Port 3000 not in use"
            echo "Checking for any error logs..."
            if [ -f "npm-debug.log" ]; then
              cat npm-debug.log
            fi
            exit 1
          fi
        env:
          CI: true
          BROWSER: none
          REACT_APP_API_URL: "http://localhost:8000"

      - name: Run accessibility tests
        run: |
          cd frontend
          npm run test:validation
        env:
          CI: true
          TEST_ACCESSIBILITY: true
        timeout-minutes: 10

      - name: Upload accessibility test results
        uses: actions/upload-artifact@v4.6.2
        if: always()
        with:
          name: accessibility-test-results
          path: frontend/accessibility-results/
